use_frameworks!

platform :ios, '9.0'

target 'HoneyWellLibrary_Example' do
  pod 'HoneyWellLibrary', :path => '../'

  target 'HoneyWellLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
